In [24]:
import numpy as np
from numpy.linalg import norm
import pickle
from tqdm import tqdm,tqdm_notebook
import os
import time
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input

In [25]:
model = ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))

94765736/94765736 [==============================] - 4s 0us/step


In [32]:
def extract_features(img_path,model):
  input_shape = (224,224,3)
  img = image.load_img(img_path,target_size=(input_shape[0],input_shape[1]))
  img_array = image.img_to_array(img)
  expanded_img_array = np.expand_dims(img_array,axis=0)
  preprocessed_img = preprocess_input(expanded_img_array)

  features = model.predict(preprocessed_img)
  flattened_features = features.flatten()
  normalized_features = flattened_features/norm(flattened_features)
  return normalized_features


In [40]:
import os
feature_list=[AssertionError]
images_path = '/content/sample_data/Data'
for file_name in os.listdir(images_path):
  features_vector = extract_features(os.path.join(images_path,file_name),model)
  feature_list.append(features_vector)



1/1 [==============================] - 0s 204ms/step


In [38]:
import sklearn
print (sklearn.__version__) # this causes the problem!


1.2.2


In [50]:
import sklearn
from sklearn.decomposition import PCA




# Convert feature_list to a numpy array
feature_list = np.array(feature_list)

# Apply PCA for dimensionality reduction
num_features_dimensions = 100  # Choose the desired number of dimensions
pca = PCA(n_components=num_features_dimensions)
pca.fit(feature_list)
feature_list_compressed = pca.transform(feature_list)

<ipython-input-50-c4eaec779bbc>:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  feature_list = np.array(feature_list)


TypeError: ignored

In [53]:
import os
import numpy as np
from sklearn.decomposition import PCA
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.applications import VGG16

# Assuming you have a function 'extract_features' defined to extract features
def extract_features(image_path, model):
    img = image.load_img(image_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)
    features = model.predict(img_array)
    return features.flatten()  # Flatten to a 1D array

model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

feature_list = []  # List to store extracted features

images_path = '/content/sample_data/Data'
for file_name in os.listdir(images_path):
    if file_name.endswith('.jpg') or file_name.endswith('.png'):
        features_vector = extract_features(os.path.join(images_path, file_name), model)
        feature_list.append(features_vector)

# Convert feature_list to a numpy array
feature_list = np.array(feature_list)

# Apply PCA for dimensionality reduction
num_features_dimensions = min(feature_list.shape[0], feature_list.shape[1])  # Maximum possible components
pca = PCA(n_components=num_features_dimensions)
pca.fit(feature_list)
feature_list_compressed = pca.transform(feature_list)

print("Original shape:", feature_list.shape)
print("Compressed shape:", feature_list_compressed.shape)
print(feature_list_compressed)



1/1 [==============================] - 1s 556ms/step
Original shape: (3, 25088)
Compressed shape: (3, 3)
[[-5.9437462e+01  9.3398547e+02  6.1099231e-04]
 [-1.0343540e+03 -5.0612045e+02  1.0210611e-03]
 [ 1.0937913e+03 -4.2786496e+02 -1.6225651e-03]]
